[versions]

# Plugins
agp = "8.3.2"
kotlin = "1.9.23"

# Core Dependencies
core-ktx = "1.13.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
androidx-test-espresso-core = "3.5.1"
androidx-appcompat-version = "1.6.1"
lifecycle-runtime-ktx = "2.7.0"
lifecycle-runtime-compose = "2.7.0"
lifecycle-viewmodel-compose = "2.7.0"
material = "1.11.0"

# Compose Dependencies
activity-compose = "1.9.0"
navigation-compose = "2.7.7"
compose-compiler-version = "1.5.12"
compose-version = "1.6.6"
compose-m3-version = "1.2.1"



[libraries]

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat-version" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-version" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-version" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-version" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-version" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-version" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-version" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-version" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-version" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-m3-version" }



[plugins]

androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }



[bundles]