name: Publish library

on:
  workflow_dispatch:

jobs:
  # Took it from https://github.com/chrisbanes/haze/blob/main/.github/workflows/build.yml
  deploy:
    runs-on: macos-14
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - uses: gradle/gradle-build-action@v3.5.0
      
      - name: Build
        run: ./gradlew build
        
      
