name: Hello World

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        type: string
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Edit Toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "gradle/libs.versions.toml"
          key: "versions.test"
          value: "${{ inputs.version }}"
