name: Hello World

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        type: string
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
           ref: master
    - name: Verify gradle directory
      run: ls -R gradle || echo "Directory does not exist"
      
    - name: toml editor 
      uses: rahulp959/toml-editor@v1.0.1


      with:
          file: "gradle/libs.versions.toml"
          key: "versions.test"
          value: "${{ inputs.version }}"
