name: Hello World

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        type: string

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Edit TOML file
      uses: rahulp959/toml-editor@v1.0.1
      with:
        file: "gradle/libs.versions.toml"
        key: "versions.test"
        value: "${{ inputs.version }}"

    - name: Display Updated TOML File
      run: cat gradle/libs.versions.toml
